# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='Activity Name')),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('perspective_selection', models.CharField(choices=[('Learner Selected', 'Learner Selected'), ('Randomly Assigned', 'Randomly Assigned'), ('Learner Completes All Perspectives', 'Learner Completes All Perspectives')], default='Randomly Assigned', max_length=100)),
                ('enable_curation', models.CharField(choices=[('Allow learners to choose a perspective to curate', 'Allow learners to choose a perspective to curate'), ('Randomly assign a perspective that learners have not attempted for curation', 'Randomly assign a perspective that learners have not attempted for curation'), ('Allow Learners to curate all perspectives', 'Allow Learners to curate all perspectives')], default='Randomly assign a perspective that learners have not attempted for curation', max_length=100)),
                ('view_knowledge_base_before_sumbmission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution_score', models.IntegerField(default=50)),
                ('curation_score', models.IntegerField(default=50)),
                ('minimum_contribution', models.IntegerField(default=3)),
                ('minimum_curation', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['template', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CuratedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='No Comment', max_length=5000)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['curator', 'item', 'comment'],
            },
        ),
        migrations.CreateModel(
            name='LearnerPerspectiveSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing', models.CharField(choices=[("Don't Share", "Don't Share"), ('Share Anonymously', 'Share Anonymously'), ('Share with other learners', 'Share with other learners')], default='Share with other learners', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspectivesx.Activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learner Submissions',
                'ordering': ['activity', 'created_by'],
            },
        ),
        migrations.CreateModel(
            name='LearnerSubmissionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=5000, verbose_name='Item Name')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_times_curated', models.IntegerField(default=0)),
                ('learner_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspectivesx.LearnerPerspectiveSubmission')),
            ],
            options={
                'verbose_name_plural': 'Learner Submission Items',
                'ordering': ['learner_submission', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_grade', models.IntegerField(default=0)),
                ('curation_grade', models.IntegerField(default=0)),
                ('total_grade', models.IntegerField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perspectivesx.LearnerPerspectiveSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Template Name')),
                ('description', models.TextField()),
                ('icon', models.ImageField(default='', upload_to='icons')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Item Name')),
                ('color', models.CharField(default='#ff0000', max_length=7)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspectivesx.Template')),
            ],
            options={
                'verbose_name_plural': 'Template Items',
                'ordering': ['template', 'position'],
            },
        ),
        migrations.AddField(
            model_name='learnerperspectivesubmission',
            name='selected_perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspectivesx.TemplateItem'),
        ),
        migrations.AddField(
            model_name='curateditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspectivesx.LearnerSubmissionItem'),
        ),
        migrations.AddField(
            model_name='activity',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspectivesx.Template'),
        ),
        migrations.AlterUniqueTogether(
            name='learnerperspectivesubmission',
            unique_together=set([('activity', 'created_by', 'selected_perspective')]),
        ),
        migrations.AlterUniqueTogether(
            name='curateditem',
            unique_together=set([('item', 'curator')]),
        ),
    ]
