# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perspectivesx', '0003_auto_20180119_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionscore',
            name='submission',
        ),
        migrations.AddField(
            model_name='submissionscore',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
