# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perspectivesx', '0004_auto_20180122_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='icon_large',
            field=models.CharField(default='path', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateitem',
            name='icon_small',
            field=models.CharField(default='path', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionscore',
            name='total_grade',
            field=models.IntegerField(default=0),
        ),
    ]
