# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perspectivesx', '0005_auto_20180131_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateitem',
            name='icon_large',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='icon_small',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
