# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perspectivesx', '0006_auto_20180131_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='enable_curation',
        ),
        migrations.AddField(
            model_name='activity',
            name='enable_search',
            field=models.BooleanField(default=False),
        ),
    ]
